name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "Verzeichnisinhalt nach Build:"
          ls -la

      - name: Verify Build Directory
        run: |
          echo "Checking build directory..."
          ls -la build/
          if [ ! -d build ]; then
            echo "Build directory not found, exiting..."
            exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Überprüfe Artefakt-Download
        run: |
          if [ ! -d build ]; then
            echo "Fehler: Build-Artefakt wurde nicht korrekt heruntergeladen!"
            exit 1
          fi

      - name: Debug Verify Artifact Download
        run: |
          echo "Inhalt des Root-Verzeichnisses nach Download:"
          ls -la
          echo "Inhalt des build-Verzeichnisses:"
          ls -la build || echo "Das Verzeichnis 'build' existiert nicht!"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          if [ ! -d build ]; then
            echo "Fehler: Build-Verzeichnis fehlt. Abbruch!"
            exit 1
          fi
          netlify deploy --dir=build --prod
